export const ORBIT_THEME_NAME = "orbit-dark";

export const orbitMonacoTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "comment", foreground: "5C5F66" },
    { token: "keyword", foreground: "E0898B" },
    { token: "storage", foreground: "E0898B" },
    { token: "string", foreground: "A9C48E" },
    { token: "number", foreground: "D9A85C" },
    { token: "constant.numeric", foreground: "D9A85C" },
    { token: "entity.name.function", foreground: "8FB8D9" },
    { token: "support.function", foreground: "8FB8D9" },
    { token: "variable.other.property", foreground: "8FB8D9" },
    { token: "delimiter", foreground: "7A7C82" },
    { token: "punctuation", foreground: "7A7C82" },
    { token: "identifier", foreground: "C9C8C4" },
    { token: "variable", foreground: "C9C8C4" },
    { token: "tag", foreground: "E0898B" },
    { token: "attribute.name", foreground: "D9A85C" },
    { token: "attribute.value", foreground: "A9C48E" },
    { token: "keyword.other.unit.css", foreground: "D9A85C" },
    { token: "keyword.control.at-rule.css", foreground: "C9A0C9" },
  ],
  colors: {
    "editor.background": "#101114",
    "editor.foreground": "#C9C8C4",
    "editorLineNumber.foreground": "#45474D",
    "editorLineNumber.activeForeground": "#E8833A",
    "editorCursor.foreground": "#E8833A",
    "editor.lineHighlightBackground": "#E8833A0D",
    "editor.selectionBackground": "#E8833A47",
    "editor.inactiveSelectionBackground": "#E8833A24",
    "editorIndentGuide.background1": "#1C1E22",
    "editorIndentGuide.activeBackground1": "#2A2C31",
    "editorWhitespace.foreground": "#1F2126",
    "editor.findMatchBackground": "#E8833A38",
    "editor.findMatchHighlightBackground": "#E8833A24",
    "editorBracketMatch.background": "#E8833A1F",
    "editorBracketMatch.border": "#E8833A",
    "scrollbarSlider.background": "#2A2C3199",
    "scrollbarSlider.hoverBackground": "#3A3D44AA",
    "minimap.background": "#0F1013",
  },
};
